[project]
site_name = "execsql2"
site_author = "Caleb Grant"
site_description = "A multi-DBMS SQL script processor"
site_url = "https://execsql2.readthedocs.io/"
repo_url = "https://github.com/geocoug/execsql2"
repo_name = "geocoug/execsql2"
docs_dir = "docs"
copyright = "Copyright &copy; 2007-2025 R.Dreas Nielsen, 2026-present Caleb Grant"
nav = [
    { "Home" = "index.md" },
    { "Getting Started" = [
        { "Installation" = "getting-started/installation.md" },
        { "Requirements" = "getting-started/requirements.md" },
        { "Syntax & Options" = "getting-started/syntax.md" }
    ] },
    { "Reference" = [
        { "Configuration" = "reference/configuration.md" },
        { "Substitution Variables" = "reference/substitution_vars.md" },
        { "Metacommands" = "reference/metacommands.md" },
        { "Security" = "reference/security.md" }
    ] },
    { "Guides" = [
        { "Usage Notes" = "guides/usage.md" },
        { "SQL Syntax Notes" = "guides/sql_syntax.md" },
        { "Logging" = "guides/logging.md" },
        { "Character Encoding" = "guides/encoding.md" },
        { "Using Script Files" = "guides/using_scripts.md" },
        { "Documenting Script Actions" = "guides/documentation.md" },
        { "Debugging" = "guides/debugging.md" },
        { "execsql-format" = "guides/formatter.md" },
        { "Examples" = "guides/examples.md" }
    ] },
    { "Contributing" = [
        { "Adding Metacommands" = "dev/adding_metacommands.md" },
        { "Adding Exporters" = "dev/adding_exporters.md" },
        { "Adding Database Adapters" = "dev/adding_db_adapters.md" },
        { "Adding Importers" = "dev/adding_importers.md" }
    ] },
    { "API Reference" = [
        { "Overview" = "api/index.md" },
        { "CLI" = "api/cli.md" },
        { "Databases" = "api/db.md" },
        { "Exporters" = "api/exporters.md" },
        { "Importers" = "api/importers.md" },
        { "Metacommands" = "api/metacommands.md" }
    ] },
    { "About" = [
        { "Copyright" = "about/copyright.md" },
        { "Contributors" = "about/contributors.md" },
        { "Change Log" = "about/change_log.md" }
    ] }
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
show_source = false
show_if_no_docstring = true
merge_init_into_class = true
show_signature_annotations = false

[project.theme]
# variant = "classic" # Use for old material theme
features = [
    "navigation.footer",
    "navigation.tabs",
    "navigation.sections",
    "navigation.path"
]

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
