"""execsql metacommand dispatch table.

Importing this module populates a MetaCommandList (``DISPATCH_TABLE``) with
every metacommand regex and its handler function.  The dispatch table is
consumed by script.MetacommandStmt.run() via ``_state.metacommandlist``.

Handler functions live in the sibling modules:
  connect, conditions, control, data, debug, io, prompt, script_ext, system
"""

from __future__ import annotations

import execsql.state as _state

# Handler imports — grouped by module for readability.
from execsql.metacommands.connect import (
    x_connect_pg,
    x_connect_user_pg,
    x_connect_ssvr,
    x_connect_user_ssvr,
    x_connect_mysql,
    x_connect_user_mysql,
    x_connect_access,
    x_connect_fb,
    x_connect_user_fb,
    x_connect_ora,
    x_connect_user_ora,
    x_connect_duckdb,
    x_connect_sqlite,
    x_connect_dsn,
    x_use,
    x_disconnect,
    x_autocommit_on,
    x_autocommit_off,
    x_pg_vacuum,
    x_daoflushdelay,
)
from execsql.metacommands.control import (
    x_assert,
    x_if,
    x_if_orif,
    x_if_andif,
    x_if_elseif,
    x_if_else,
    x_if_block,
    x_if_end,
    x_loop,
    x_halt,
    x_halt_msg,
    x_error_halt,
    x_metacommand_error_halt,
    x_begin_batch,
    x_end_batch,
    x_rollback,
    x_break,
    x_wait_until,
)
from execsql.metacommands.data import (
    x_sub,
    x_sub_add,
    x_sub_append,
    x_sub_empty,
    x_rm_sub,
    x_sub_local,
    x_sub_tempfile,
    x_sub_ini,
    x_sub_querystring,
    x_sub_encrypt,
    x_sub_decrypt,
    x_subdata,
    x_selectsub,
    x_prompt_selectsub,
    x_empty_strings,
    x_trim_strings,
    x_replace_newlines,
    x_empty_rows,
    x_only_strings,
    x_boolean_int,
    x_boolean_words,
    x_fold_col_hdrs,
    x_trim_col_hdrs,
    x_clean_col_hdrs,
    x_del_empty_cols,
    x_create_col_hdrs,
    x_dedup_col_hdrs,
    x_import_common_cols_only,
    x_quote_all_text,
    x_reset_counter,
    x_reset_counters,
    x_set_counter,
    x_max_int,
)
from execsql.metacommands.debug import (
    x_debug_write_metacommands,
    x_debug_commandliststack,
    x_debug_iflevels,
    x_debug_write_odbc_drivers,
    x_debug_log_subvars,
    x_debug_log_config,
    x_debug_write_subvars,
    x_debug_write_config,
)
from execsql.debug.repl import x_breakpoint
from execsql.metacommands.io import (
    x_export,
    x_export_query,
    x_export_query_with_template,
    x_export_with_template,
    x_export_ods_multiple,
    x_export_xlsx_multiple,
    x_export_metadata,
    x_export_metadata_table,
    x_import,
    x_import_file,
    x_import_ods,
    x_import_ods_pattern,
    x_import_xls,
    x_import_xls_pattern,
    x_import_parquet,
    x_import_feather,
    x_import_json,
    x_import_row_buffer,
    x_show_progress,
    x_export_row_buffer,
    x_write,
    x_write_create_table,
    x_write_create_table_ods,
    x_write_create_table_xls,
    x_write_create_table_alias,
    x_write_prefix,
    x_write_suffix,
    x_writescript,
    x_include,
    x_copy,
    x_copy_query,
    x_zip,
    x_zip_buffer_mb,
    x_rm_file,
    x_make_export_dirs,
    x_cd,
    x_scan_lines,
    x_hdf5_text_len,
    x_serve,
)
from execsql.metacommands.prompt import (
    x_prompt,
    x_prompt_enter,
    x_prompt_entryform,
    x_prompt_pause,
    x_prompt_compare,
    x_prompt_ask_compare,
    x_prompt_ask,
    x_prompt_map,
    x_prompt_action,
    x_prompt_savefile,
    x_prompt_openfile,
    x_prompt_directory,
    x_prompt_select_rows,
    x_prompt_credentials,
    x_prompt_connect,
    x_ask,
    x_pause,
    x_msg,
    x_reset_dialog_canceled,
)
from execsql.metacommands.script_ext import (
    x_extendscript,
    x_extendscript_metacommand,
    x_extendscript_sql,
    x_executescript,
)
from execsql.metacommands.upsert import (
    x_pg_upsert,
    x_pg_upsert_check,
    x_pg_upsert_qa,
)
from execsql.metacommands.system import (
    x_system_cmd,
    x_email,
    x_timer,
    x_log,
    x_logwritemessages,
    x_log_datavars,
    x_log_sql,
    x_console,
    x_consoleprogress,
    x_consolewait,
    x_consolewait_onerror,
    x_consolewait_whendone,
    x_console_hideshow,
    x_consolewidth,
    x_consoleheight,
    x_consolestatus,
    x_consolesave,
    x_cancel_halt,
    x_cancel_halt_write_clear,
    x_cancel_halt_write,
    x_cancel_halt_email_clear,
    x_cancel_halt_email,
    x_cancel_halt_exec,
    x_cancel_halt_exec_clear,
    x_error_halt_write_clear,
    x_error_halt_write,
    x_error_halt_email_clear,
    x_error_halt_email,
    x_error_halt_exec,
    x_error_halt_exec_clear,
    x_write_warnings,
    x_gui_level,
    x_execute,
)

# Regex helper functions (from utils/regex.py)
from execsql.utils.regex import (
    ins_rxs,
    ins_quoted_rx,
    ins_schema_rxs,
    ins_table_rxs,
    ins_table_list_rxs,
    ins_fn_rxs,
)
from execsql.script import MetaCommandList

__all__ = [
    # execsql.state
    "_state",
    # connect handlers
    "x_connect_pg",
    "x_connect_user_pg",
    "x_connect_ssvr",
    "x_connect_user_ssvr",
    "x_connect_mysql",
    "x_connect_user_mysql",
    "x_connect_access",
    "x_connect_fb",
    "x_connect_user_fb",
    "x_connect_ora",
    "x_connect_user_ora",
    "x_connect_duckdb",
    "x_connect_sqlite",
    "x_connect_dsn",
    "x_use",
    "x_disconnect",
    "x_autocommit_on",
    "x_autocommit_off",
    "x_pg_vacuum",
    "x_daoflushdelay",
    # control handlers
    "x_assert",
    "x_if",
    "x_if_orif",
    "x_if_andif",
    "x_if_elseif",
    "x_if_else",
    "x_if_block",
    "x_if_end",
    "x_loop",
    "x_halt",
    "x_halt_msg",
    "x_error_halt",
    "x_metacommand_error_halt",
    "x_begin_batch",
    "x_end_batch",
    "x_rollback",
    "x_break",
    "x_wait_until",
    # data handlers
    "x_sub",
    "x_sub_add",
    "x_sub_append",
    "x_sub_empty",
    "x_rm_sub",
    "x_sub_local",
    "x_sub_tempfile",
    "x_sub_ini",
    "x_sub_querystring",
    "x_sub_encrypt",
    "x_sub_decrypt",
    "x_subdata",
    "x_selectsub",
    "x_prompt_selectsub",
    "x_empty_strings",
    "x_trim_strings",
    "x_replace_newlines",
    "x_empty_rows",
    "x_only_strings",
    "x_boolean_int",
    "x_boolean_words",
    "x_fold_col_hdrs",
    "x_trim_col_hdrs",
    "x_clean_col_hdrs",
    "x_del_empty_cols",
    "x_create_col_hdrs",
    "x_dedup_col_hdrs",
    "x_import_common_cols_only",
    "x_quote_all_text",
    "x_reset_counter",
    "x_reset_counters",
    "x_set_counter",
    "x_max_int",
    # debug handlers
    "x_debug_write_metacommands",
    "x_debug_commandliststack",
    "x_debug_iflevels",
    "x_debug_write_odbc_drivers",
    "x_debug_log_subvars",
    "x_debug_log_config",
    "x_debug_write_subvars",
    "x_debug_write_config",
    # debug repl handlers
    "x_breakpoint",
    # io handlers
    "x_export",
    "x_export_query",
    "x_export_query_with_template",
    "x_export_with_template",
    "x_export_ods_multiple",
    "x_export_xlsx_multiple",
    "x_export_metadata",
    "x_export_metadata_table",
    "x_import",
    "x_import_file",
    "x_import_ods",
    "x_import_ods_pattern",
    "x_import_xls",
    "x_import_xls_pattern",
    "x_import_parquet",
    "x_import_feather",
    "x_import_json",
    "x_import_row_buffer",
    "x_show_progress",
    "x_export_row_buffer",
    "x_write",
    "x_write_create_table",
    "x_write_create_table_ods",
    "x_write_create_table_xls",
    "x_write_create_table_alias",
    "x_write_prefix",
    "x_write_suffix",
    "x_writescript",
    "x_include",
    "x_copy",
    "x_copy_query",
    "x_zip",
    "x_zip_buffer_mb",
    "x_rm_file",
    "x_make_export_dirs",
    "x_cd",
    "x_scan_lines",
    "x_hdf5_text_len",
    "x_serve",
    # prompt handlers
    "x_prompt",
    "x_prompt_enter",
    "x_prompt_entryform",
    "x_prompt_pause",
    "x_prompt_compare",
    "x_prompt_ask_compare",
    "x_prompt_ask",
    "x_prompt_map",
    "x_prompt_action",
    "x_prompt_savefile",
    "x_prompt_openfile",
    "x_prompt_directory",
    "x_prompt_select_rows",
    "x_prompt_credentials",
    "x_prompt_connect",
    "x_ask",
    "x_pause",
    "x_msg",
    "x_reset_dialog_canceled",
    # script_ext handlers
    "x_extendscript",
    "x_extendscript_metacommand",
    "x_extendscript_sql",
    "x_executescript",
    # system handlers
    "x_system_cmd",
    "x_email",
    "x_timer",
    "x_log",
    "x_logwritemessages",
    "x_log_datavars",
    "x_log_sql",
    "x_console",
    "x_consoleprogress",
    "x_consolewait",
    "x_consolewait_onerror",
    "x_consolewait_whendone",
    "x_console_hideshow",
    "x_consolewidth",
    "x_consoleheight",
    "x_consolestatus",
    "x_consolesave",
    "x_cancel_halt",
    "x_cancel_halt_write_clear",
    "x_cancel_halt_write",
    "x_cancel_halt_email_clear",
    "x_cancel_halt_email",
    "x_cancel_halt_exec",
    "x_cancel_halt_exec_clear",
    "x_error_halt_write_clear",
    "x_error_halt_write",
    "x_error_halt_email_clear",
    "x_error_halt_email",
    "x_error_halt_exec",
    "x_error_halt_exec_clear",
    "x_write_warnings",
    "x_gui_level",
    "x_execute",
    # upsert handlers
    "x_pg_upsert",
    "x_pg_upsert_check",
    "x_pg_upsert_qa",
    # regex helpers
    "ins_rxs",
    "ins_quoted_rx",
    "ins_schema_rxs",
    "ins_table_rxs",
    "ins_table_list_rxs",
    "ins_fn_rxs",
    # MetaCommandList
    "MetaCommandList",
    # format constants
    "DELIMITED_FORMATS",
    "TEXT_FORMATS",
    "JSON_VARIANT_FORMATS",
    "QUERY_EXPORT_FORMATS",
    "TABLE_EXPORT_FORMATS",
    "SERVE_FORMATS",
    "METADATA_FORMATS",
    "ALL_EXPORT_FORMATS",
    "DATABASE_TYPES",
    # dispatch
    "build_dispatch_table",
    "DISPATCH_TABLE",
]

# ---------------------------------------------------------------------------
# Export format constants — single source of truth.
# Used in dispatch table regex patterns and by io_export.py for validation.
# ---------------------------------------------------------------------------
DELIMITED_FORMATS = ["CSV", "TAB", "TSV", "TABQ", "TSVQ", "UNITSEP", "US"]
TEXT_FORMATS = ["TXT", "TXT-AND", "PLAIN"]
JSON_VARIANT_FORMATS = ["JSON_TS", "JSON_TABLESCHEMA"]

QUERY_EXPORT_FORMATS = (
    DELIMITED_FORMATS
    + TEXT_FORMATS
    + ["ODS", "XLSX", "JSON", "HTML", "CGI-HTML", "VALUES", "LATEX", "RAW", "B64", "FEATHER", "YAML", "MARKDOWN", "MD"]
)
TABLE_EXPORT_FORMATS = (
    DELIMITED_FORMATS
    + TEXT_FORMATS
    + [
        "JSON",
        "XML",
        "VALUES",
        "HTML",
        "CGI-HTML",
        "SQLITE",
        "DUCKDB",
        "LATEX",
        "RAW",
        "B64",
        "FEATHER",
        "HDF5",
        "XLSX",
        "YAML",
        "MARKDOWN",
        "MD",
    ]
)
SERVE_FORMATS = ["BINARY", "CSV", "TXT", "TEXT", "ODS", "JSON", "HTML", "PDF", "ZIP"]
METADATA_FORMATS = ["CSV", "TAB", "TSV", "TABQ", "TSVQ", "TXT", "TEXT"]
ALL_EXPORT_FORMATS = sorted(
    set(QUERY_EXPORT_FORMATS + TABLE_EXPORT_FORMATS + JSON_VARIANT_FORMATS),
)

DATABASE_TYPES = [
    "POSTGRESQL",
    "MYSQL",
    "MARIADB",
    "ORACLE",
    "SQLSERVER",
    "FIREBIRD",
    "ACCESS",
    "DUCKDB",
    "SQLITE",
    "DSN",
]


# ---------------------------------------------------------------------------
# Module-level DISPATCH_TABLE — built once at import time.
# Metacommand plugins (if any) are discovered and registered after the
# built-in table is constructed.
# ---------------------------------------------------------------------------
from execsql.metacommands.dispatch import build_dispatch_table

DISPATCH_TABLE = build_dispatch_table()

# Discover and register metacommand plugins via entry points.
# This runs at import time so plugins are available before any script runs.
from execsql.plugins import discover_metacommand_plugins

discover_metacommand_plugins(DISPATCH_TABLE)
